# Generated by Django 4.0.3 on 2022-04-07 10:14

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('uid', models.UUIDField(blank=True, default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='UID')),
                ('name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Организация')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('uid', models.UUIDField(blank=True, default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='UID')),
                ('name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Название услуги')),
                ('cost', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8, verbose_name='Цена услуги')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.company', verbose_name='Организация')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('uid', models.UUIDField(blank=True, default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='UID')),
                ('status', models.CharField(choices=[('0', '0'), ('1', '1')], default=('0', '0'), max_length=150)),
                ('grade', models.IntegerField(verbose_name='Оценка')),
                ('comment', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Отзыв')),
                ('file', models.FileField(blank=True, null=True, upload_to='', verbose_name='Файлы')),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.service', verbose_name='Услуги')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Заказчик')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('uid', models.UUIDField(blank=True, default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='UID')),
                ('sum', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Стоимость')),
                ('service_request', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.servicerequest', verbose_name='Заявка')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='user',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.company', verbose_name='Обслуживающая организация'),
        ),
    ]
