# Generated by Django 4.0.3 on 2022-04-08 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_servicerequest_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='icon',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Название иконки в статике'),
        ),
    ]
